version: '3.8'

services:
  mysql-master:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    volumes:
      - mysql-master-data:/var/lib/mysql
      - ./master/conf:/etc/mysql/conf.d
      - ./master/user-create-and-seed.sql:/etc/mysql/user-create-and-seed.sql
    ports:
      - "3306:3306"

  mysql-slave:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    volumes:
      - mysql-slave-data:/var/lib/mysql
      - ./slave/conf:/etc/mysql/conf.d
    ports:
      - "3307:3306"

volumes:
  mysql-master-data:
  mysql-slave-data:

